django/core/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('error/', views.error),
    path('headers/', views.headers),
    path('polls/', include('polls.urls')),
    path('', lambda r: HttpResponseRedirect('polls/')),
]

django/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:question_id>/results/', views.results, name='results'),
]

django/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    label = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.label

django/core/views.py
from django.shortcuts import render


def error(request):
    '''Intentionally raise an exception.'''
    raise Exception('The error view was called!')


def headers(request):
    '''Display the HTTP headers on the incoming request.'''
    headers = sorted(request.META.items())
    return render(request, 'core/headers.html', {'headers': headers})

django/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from .models import Choice
from .models import Question


def index(request):
    '''Return the last 5 published questions.'''

    # Do not include questions set to be published in the future
    questions = Question.objects \
        .filter(pub_date__lte=timezone.now()) \
        .order_by('-pub_date')[:5]

    return render(request, 'polls/index.html', {'questions': questions})


def detail(request, question_id):
    '''Return a form for the user to vote on the question.'''

    # Exclude any questions that aren't published yet.
    queryset = Question.objects.filter(pub_date__lte=timezone.now())

    context = {
        'question': get_object_or_404(queryset, pk=question_id),
    }

    return render(request, 'polls/detail.html', context)


def vote(request, question_id):
    '''Receive a submitted form and record the vote for the question.'''

    # Exclude any questions that aren't published yet.
    queryset = Question.objects.filter(pub_date__lte=timezone.now())
    question = get_object_or_404(queryset, pk=question_id)

    try:
        choice = question.choices.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Please select a choice.",
        })

    else:
        choice.votes += 1
        choice.save()

        # Always return an HttpResponseRedirect after successfully dealing with POST data.
        # This prevents data from being posted twice if a user hits the back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    '''Display the voting results for the question.'''

    # Exclude any questions that aren't published yet.
    queryset = Question.objects.filter(pub_date__lte=timezone.now())
    question = get_object_or_404(queryset, pk=question_id)

    return render(request, 'polls/results.html', {'question': question})

django/polls/templates/polls/detail.html
{% extends "core/base.html" %}

{% block content %}

<h1 class="mb-4">{{ question.question_text }}</h1>

{% if error_message %}
<p><strong style="color: red">{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post" id="choice-form">
    {% csrf_token %}

    {% for choice in question.choices.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.label }}</label><br>
    {% endfor %}

    <input type="submit" value="Vote" class="mt-3">
</form>

{% endblock %}

django/polls/templates/polls/index.html
{% extends "core/base.html" %}

{% block content %}

<h1 class="mb-4">Latest Polls</h1>

{% if questions %}
<ul>
    {% for question in questions %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">
            {{ question.question_text }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are currently no polls available.</p>
{% endif %}

{% endblock %}

django/polls/templates/polls/results.html
{% extends "core/base.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<table class="my-4">
    <tr>
        <th class="pr-5">Choice</th>
        <th class="pr-5">Votes</th>
    </tr>

    {% for choice in question.choices.all %}
    <tr>
        <td class="pr-5">{{ choice.label }}</td>
        <td class="pr-5">{{ choice.votes }}</td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'polls:index' %}">Vote again?</a>

{% endblock %}

django/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Django Docker</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<body class="container-fluid my-5">
    <div class="px-5">{% block content %}{% endblock %}</div>
</body>

</html>

django/templates/core/headers.html
{% extends "core/base.html" %}

{% block content %}

<h1 class="mb-4">HTTP Headers ({{ headers|length }})</h1>

{% if headers %}
<table class="my-4">
    <tr>
        <th class="pr-5">Name</th>
        <th class="pr-5">Value</th>
    </tr>
    {% for name, value in headers %}
    <tr>
        <td class="pr-5">{{ name }}</td>
        <td class="pr-5">{{ value }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>There are no HTTP headers to display.</p>
{% endif %}

{% endblock %}